// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QyonAdventureWorks.Data.Context;

namespace QyonAdventureWorks.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    partial class MeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QyonAdventureWorks.Business.Models.Competidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<decimal>("TemperaturaMediaCorpo")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("QyonAdventureWorks.Business.Models.HistoricoCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompetidorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCorrida")
                        .HasColumnType("datetime");

                    b.Property<int>("PistaCorridaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TempoGasto")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("CompetidorId");

                    b.HasIndex("PistaCorridaId")
                        .IsUnique();

                    b.ToTable("HistoricoCorridas");
                });

            modelBuilder.Entity("QyonAdventureWorks.Business.Models.PistaCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PistaCorridas");
                });

            modelBuilder.Entity("QyonAdventureWorks.Business.Models.HistoricoCorrida", b =>
                {
                    b.HasOne("QyonAdventureWorks.Business.Models.Competidor", "Competidor")
                        .WithMany("HistoricoCorridas")
                        .HasForeignKey("CompetidorId")
                        .IsRequired();

                    b.HasOne("QyonAdventureWorks.Business.Models.PistaCorrida", "PistaCorrida")
                        .WithOne("HistoricoCorrida")
                        .HasForeignKey("QyonAdventureWorks.Business.Models.HistoricoCorrida", "PistaCorridaId")
                        .IsRequired();

                    b.Navigation("Competidor");

                    b.Navigation("PistaCorrida");
                });

            modelBuilder.Entity("QyonAdventureWorks.Business.Models.Competidor", b =>
                {
                    b.Navigation("HistoricoCorridas");
                });

            modelBuilder.Entity("QyonAdventureWorks.Business.Models.PistaCorrida", b =>
                {
                    b.Navigation("HistoricoCorrida");
                });
#pragma warning restore 612, 618
        }
    }
}
